---

# this file is for the labeler workflow job
# Documentation https://github.com/marketplace/actions/labeler

"type: documentation":
  - changed-files:
      - any-glob-to-any-file: ['assets/**/*', '.github/*.yml', './*.md']

"type: maintenance":
  - changed-files:
      - any-glob-to-any-file: ['.dependabot/*', '.github/workflows/*', 'src/**/goss.yaml.j2']

...
