---

- name: Create dist directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    recurse: true
  with_items:
    - "{{ tpl_directories }}"

- name: Get latest pnpm version
  ansible.builtin.shell: cat ./../package.json | jq -r '.dependencies."pnpm"'
  register: pnpm_version
  changed_when: false

- name: Set pnpm_version
  set_fact:
    pnpm_version: "{{ pnpm_version.stdout | regex_replace('^(\\^)', '') }}"

- name: Generate Dockerfiles
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode: 0644
  with_items:
    - "{{ tpl_dockerfiles }}"

- name: Generate Dockerfile dgoss tests
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode:  0644
  with_items:
    - "{{ tpl_docker_tests }}"

...
